## One Class SVM For Normal Data

In [72]:
import pandas as pd
import numpy as np
from sklearn import svm
X_test=pd.read_csv("gener_normal.csv")
#Y_1=pd.read_csv("y_train1.csv")
train_feature=pd.read_csv("x_test_normal.csv")


In [73]:
X_test = X_test.drop(['Unnamed: 0'],axis=1)
print(X_test.shape)

(10000, 121)


In [74]:
y_1=np.ones((10000,), dtype=int)

In [75]:
Y_test= pd.DataFrame(y_1)
print(type(Y_test))

<class 'pandas.core.frame.DataFrame'>


In [76]:
# changing cols with rename() 

Y_test.columns=['Category']


In [77]:
one_gamma=0.0001
one_nu=0.25

In [78]:
# I have used various combination of hyperparameters like linear, rbf, poly, gamma- 0.001, 0.0001, nu- 0.25, 0.5, 0.75, 0.95
oneclass = svm.OneClassSVM(kernel='linear', gamma=0.01, nu=0.1)

In [79]:
from sklearn import svm
# Training the algorithm with the features. 
# This stage is very time consuming processes. In my laptop it took more than an hour to train for 200,000 observations. 
# For rbf, the time taken is even more.

oneclass.fit(train_feature)

OneClassSVM(cache_size=200, coef0=0.0, degree=3, gamma=0.01, kernel='linear',
      max_iter=-1, nu=0.1, random_state=None, shrinking=True, tol=0.001,
      verbose=False)

In [80]:
# Test the algorithm on the test set
fraud_pred = oneclass.predict(X_test)

In [81]:
# Check the number of outliers predicted by the algorithm

unique, counts = np.unique(fraud_pred, return_counts=True)
print (np.asarray((unique, counts)).T)

[[  -1 1343]
 [   1 8657]]


In [82]:

fraud_pred = pd.DataFrame(fraud_pred)
fraud_pred= fraud_pred.rename(columns={0: 'prediction'})

In [83]:
PP=fraud_pred[fraud_pred['prediction']==1]
NP=fraud_pred[fraud_pred['prediction']==-1]
number_test_data=10000
#print(PP.head(2))
P=PP.shape[0]
N=NP.shape[0]
print(P)

8657


In [84]:
acc=np.round(((P)/number_test_data)*100,2)

In [85]:
print(acc)

86.57


## One Class SVM for Malware Data

In [86]:
import pandas as pd
import numpy as np
from sklearn import svm
X_test1=pd.read_csv("gener_DoS.csv")
#Y_1=pd.read_csv("y_train1.csv")
train_feature1=pd.read_csv("x_test_dos_mal.csv")


In [87]:
X_test1 = X_test1.drop(['Unnamed: 0'],axis=1)
print(X_test1.shape)

(10000, 121)


In [88]:
y_2=np.ones((10000,), dtype=int)

In [89]:
Y_test1= pd.DataFrame(y_2)
print(type(Y_test1))

<class 'pandas.core.frame.DataFrame'>


In [90]:
Y_test1.columns=['Category']


In [91]:
oneclass1 = svm.OneClassSVM(kernel='linear', gamma=0.001, nu=0.00001)

In [92]:
one_gamma1=0.001
one_nu1=0.00001

In [93]:
from sklearn import svm
# Training the algorithm with the features. 
# This stage is very time consuming processes. In my laptop it took more than an hour to train for 200,000 observations. 
# For rbf, the time taken is even more.

oneclass1.fit(train_feature1)

OneClassSVM(cache_size=200, coef0=0.0, degree=3, gamma=0.001, kernel='linear',
      max_iter=-1, nu=1e-05, random_state=None, shrinking=True, tol=0.001,
      verbose=False)

In [94]:
# Test the algorithm on the test set
fraud_pred1= oneclass.predict(X_test1)

In [95]:
# Check the number of outliers predicted by the algorithm

unique, counts = np.unique(fraud_pred1, return_counts=True)
print (np.asarray((unique, counts)).T)

[[  -1 1949]
 [   1 8051]]


In [96]:

fraud_pred1 = pd.DataFrame(fraud_pred1)
fraud_pred1= fraud_pred1.rename(columns={0: 'prediction'})

In [97]:
PP1=fraud_pred[fraud_pred1['prediction']==1]
NP1=fraud_pred[fraud_pred1['prediction']==-1]
number_test_data1=10000
#print(PP.head(2))
P1=PP1.shape[0]
N1=NP1.shape[0]
print(P1)

8051


In [98]:
acc1=((P1)/number_test_data1)*100

In [99]:
print(acc1)

80.51


## One SVM for Mix Data

In [100]:
import pandas as pd
import numpy as np
from sklearn import svm
X_test2=pd.read_csv("gener_mix.csv")
#Y_1=pd.read_csv("y_train1.csv")
train_feature2=pd.read_csv("x_test_mix.csv")


In [101]:
X_test2 = X_test2.drop(['Unnamed: 0'],axis=1)

In [102]:
print(train_feature2.shape)

(9998, 121)


In [103]:
y_3=np.ones((9700,), dtype=int)

In [104]:
Y_test2= pd.DataFrame(y_3)
print(type(Y_test2))

<class 'pandas.core.frame.DataFrame'>


In [105]:
# changing cols with rename() 

Y_test2.columns=['Category']


In [106]:
oneclass2 = svm.OneClassSVM(kernel='linear', gamma=0.001, nu=0.01)

In [107]:
one_gamma2=0.001
one_nu2=0.00001

In [108]:
from sklearn import svm
# Training the algorithm with the features. 
# This stage is very time consuming processes. In my laptop it took more than an hour to train for 200,000 observations. 
# For rbf, the time taken is even more.

oneclass2.fit(train_feature2)

OneClassSVM(cache_size=200, coef0=0.0, degree=3, gamma=0.001, kernel='linear',
      max_iter=-1, nu=0.01, random_state=None, shrinking=True, tol=0.001,
      verbose=False)

In [109]:
# Test the algorithm on the test set
fraud_pred3 = oneclass2.predict(X_test2)

In [110]:
# Check the number of outliers predicted by the algorithm

unique, counts = np.unique(fraud_pred3, return_counts=True)
print (np.asarray((unique, counts)).T)

[[  -1  179]
 [   1 9521]]


In [111]:
fraud_pred3 = pd.DataFrame(fraud_pred3)
fraud_pred3= fraud_pred3.rename(columns={0: 'prediction'})

In [112]:
PP2=fraud_pred3[fraud_pred3['prediction']==1]
NP2=fraud_pred3[fraud_pred3['prediction']==-1]
number_test_data2=9700
#print(PP.head(2))
P2=PP2.shape[0]
N2=NP2.shape[0]
print(P2)

9521


In [113]:
acc2=np.round(((P2)/number_test_data2)*100,2)

In [114]:
print(acc2)

98.15


In [115]:
# Creating table using PrettyTable library
from prettytable import PrettyTable

names = ["ONESVM_normal","ONESVM_mal" ,"ONESVM_mix"]
         
    
optimal_gamma= [one_gamma,one_gamma1,one_gamma2]
optimal_nu = [one_nu,one_nu1,one_nu2]

test_auc_score = [acc,acc1,acc2]

numbering = [1,2,3]

# Initializing prettytable
ptable = PrettyTable()

# Adding columns
ptable.add_column("S.NO.",numbering)
ptable.add_column("MODEL",names)
ptable.add_column("Best Alpha",optimal_gamma)
ptable.add_column("Best Nu",optimal_nu)
ptable.add_column("Auccuracy",test_auc_score)
# Printing the Table
print(ptable)


+-------+---------------+------------+---------+-----------+
| S.NO. |     MODEL     | Best Alpha | Best Nu | Auccuracy |
+-------+---------------+------------+---------+-----------+
|   1   | ONESVM_normal |   0.0001   |   0.25  |   86.57   |
|   2   |   ONESVM_mal  |   0.001    |  1e-05  |   80.51   |
|   3   |   ONESVM_mix  |   0.001    |  1e-05  |   98.15   |
+-------+---------------+------------+---------+-----------+
